name: "Deploy"

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    name: "🚚 Deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install sshpass"
        run: "sudo apt install sshpass -y"
      - name: "Upload to server"
        run: "sshpass -p '${{ secrets.SERVER_ROOT_PASSWORD }}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null * root@${{ secrets.SERVER_IP }}:/usr/share/nginx/html/SchoolTimetable/"