name: "Deploy"

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    name: "🚚 Deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Setup SSH keys"
        run: "mkdir -p ~/.ssh && echo '${{ secrets.SERVER_PRIVATE_KEY }}' > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa"
      - name: "Upload to server"
        run: "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null * root@${{ secrets.SERVER_IP }}:/usr/share/nginx/html/SchoolTimetable/"
      - name: "Purge cloudflare cache"
        run: "curl -X POST \"https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache\" \
              -H \"Authorization: Bearer ${{ secrets.CF_API_KEY }}\" \
              -H \"Content-Type: application/json\" \
              --data '{\"purge_everything\":true}'"